---
- name: Add the user zookeeper-exporter
  user:
    name: prom
    shell: /sbin/nologin

- name: Downloading the zookeeper binary file from git-hub repo
  get_url:
    url: "https://github.com/visheshks/Third-party-Exporters/raw/master/zookeeper_exporter"
    dest: "/tmp"
    remote_src: yes
    mode: 0755

- name: Move Binary to appropriate path
  copy:
    src: "/tmp/zookeeper_exporter"
    dest: /usr/local/bin/
    remote_src: yes
    mode: 0555

- name: Create Zookeeper Exporter Service
  template:
    src: "zookeeper-exporter.j2"
    dest: /etc/systemd/system/zookeeper-exporter.service
    mode: 0755

- name: Daemon reload for Zookeeper Exporter
  systemd:
    name: zookeeper-exporter
    daemon_reload: yes

- name:  Enable Yarn Exporter service
  systemd:
    name: zookeeper-exporter
    state: started
    enabled: yes

